Adiciona testes unitários para CertificateUtil
alexferreiradev/OpenCertificate pull request #44
Opened 2021-09-06 03:59 UTC by joaomarcosribeiroc

Adiciona testes unitários para a classe utilitária CertificateUtil.
Para testar, utilize o comando: `mvn test -Dtest=CertificateUtilTest`

2021-09-10 22:32 UTC, alexferreiradev requested changes
Fiz uma sugestão para legibilidade. Contudo, não irei aprovar o PR devido faltar fazer os testes para os outros Utils: `Generator` e `Participant`. 

Nestes outros testes, será necessário o Mockito, caso não conheça, me chama no pv que te passo um overview dele. Basicamente, ele irá mocar os parametros passados.

2021-09-10 22:32 UTC, alexferreiradev commented on backend/src/test/java/dev/gojava/core/util/CertificateUtilTest.java
> +        Assertions.assertEquals(resultingFileName, new StringBuilder(fileName).append(".").append(fileExtension).toString());
Poderia melhorar a legibilidade do código aqui, usando string no expected. Geralmente em testes, o codigo inverte, geralmente é melhor manter o texto para deixar mais legivel do que tornar dinamico, pois se alguem mudar algo, vai quebrar e não passará em branco.

Por exemplo: 
`Assertions.assertEquals(resultingFileName, "filename.fileExtension");`

Desta forma, o dev bate o olho e sabe qual o retorno esperado.

2021-09-11 23:10 UTC, joaomarcosribeiroc commented on backend/src/test/java/dev/gojava/core/util/CertificateUtilTest.java
> +        Assertions.assertEquals(resultingFileName, new StringBuilder(fileName).append(".").append(fileExtension).toString());
Certo. Estarei fazendo essas melhorias.

2022-02-10 09:36 UTC, alexferreiradev commented
Como não teve commits novos, irei fechar ele para não confundir pessoal do gojava.

2022-02-10 09:36 UTC, closed without merging